config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home', to: 'home#index'
  get 'about', to: 'home#about'

  resources :articles
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :description
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  validates_presence_of :name
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("created_at desc").paginate(page: params[:page], per_page: 6)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      @article.user = current_user
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end

    private
      def check_user
        if @article.user != current_user
          flash[:danger] = "You are not authorized to perform that action"
          redirect_to articles_path
        end
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size_options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = size_options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s#{size}"
    image_tag(gravatar_url, alt: user.name, class: "img-circle",)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<div class="panel-body">
  <%= form_for(@article) do |f| %>
    <% if @article.errors.any? %>
      <div class="alert alert-danger">
        <h3><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
        <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-success btn-lg" %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading">
  <h1 class="text-center">Edit Article</h1>
</div>

<%= render 'form' %>
</div>

<br>
<div>
  [<%= link_to 'Back to all articles', articles_path %>]
</div>

app/views/articles/index.html.erb
<div class="jumbotron text-center">
  <h1>Experiment Blog</h1>
  <p>Let the world hear your views, thoughts and opinion</p>
  <p>
  <% if user_signed_in? %>
    Welcome <%= current_user.name %>, <%= link_to "Post Article", new_article_path, class: "btn btn-success btn-xs" %>
  <% else %>
    <%= link_to "Sign up now", new_user_registration_path, class: "btn btn-primary btn-lg" %> or <%= link_to "Sign in now", new_user_session_path, class: "btn btn-success btn-lg" %>
  <% end %>

  </p>
</div>

<h1 class="text-center">All Published Articles</h1>
<hr>
<div class="row">
  <% @articles.each do |article| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
         <div class="panel-title">
           <h3><%= link_to article.title, article_path(article) %></h3>
           <div class="pull-right gravatar">
            <span><%= gravatar_for(article.user) %></span>
           </div>
         </div>
        </div>
        <div class="panel-body">
         <p><%= truncate(article.description, length: 50) %></p>
        </div>
        <div class="meta-details">
          <small>Created:<em> <%= time_ago_in_words(article.created_at) %> ago by </em> <%= article.user.name %></small>
        </div>
        <div class="panel-footer">
          <%= link_to 'Read this article', article_path(article), class: "btn btn-success btn-xs" %>
        <% if article.user == current_user %>
          <%= link_to 'Edit this article', edit_article_path(article), class: "btn btn-primary btn-xs" %>
          <%= link_to 'Delete this article', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>


 <div class="text-center">
    <%= will_paginate %>
  </div>

app/views/articles/new.html.erb
<div class="panel panel-default">
<div class="panel-heading">
  <h1 class="text-center">Post New Article</h1>
</div>

<%= render 'form' %>
</div>

<br>
<div>
  [<%= link_to 'Back to all articles', articles_path %>]
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-md-2 col-md-offset-2 well text-center">
    <%= gravatar_for(@article.user)%> <br>
    <span><%= @article.user.name %> <small>(<%= pluralize(@article.user.articles.count, 'article') %>)</small></span>
    <% if @article.user == current_user %>
    <br>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary btn-xs" %> <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" %>
    <% end %>
    <%= link_to "View All Articles", articles_path, class: "btn btn-success btn-xs" %>
  </div>
  <div class="col-md-8 article-title article-description">
    <h1><%= @article.title %></h1>
    <p><%= @article.description %></p>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <h1>About us</h1>

  <p>Experiment gives authors around the world to share their views on important issues shaping the world</p>
</div>

app/views/home/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Experiment Blog</h1>
  <p>Let the world hear your views, thoughts and opinion</p>
  <p><%= link_to "Sign up now", "#", class: "btn btn-primary btn-lg" %> or <%= link_to "Sign in now", "#", class: "btn btn-success btn-lg" %></p>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="row">
    <div class="col-md-2 col-md-offset-10">
      <p>&copy; Bravo <%= Time.now.year %> | <%= link_to "About", about_path %></p>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Experiment", root_path, class: "navbar-brand text-uppercase", id: "brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Post Article", new_article_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete  %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Home", home_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if name == "notice" %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% else %>
    <%= content_tag(:div, msg, class: "alert alert-danger") %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Experiment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>

  <div class="container">
    <%= render "layouts/messages" %>
    <%= yield %>
  </div>

  <%= render "layouts/footer" %>
</body>
</html>